name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
        scala:
          - 2_11
          - 2_12
          - 2_13
          - 3
        include:
          - java: 17
            scala: 2_13
          - java: 17
            scala: 3
    env:
      REDIS_HOME: "redis-6.2.6/src"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: ./install-redis.sh
    - run: sbt scalafmtSbtCheck "SetScala${{ matrix.scala }}" scalafmtCheckAll Test/compile
    - run: sbt "SetScala${{ matrix.scala }}" test
